name: line-counter

on: push

jobs:
  line-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Line counter operation
        run: chmod +x ./script/line-counter.sh && ./script/line-counter.sh

      - name: Commit 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "report.md"
          commit_message: Updated report with line counter
